# WIP: Migrate to a new, better format
# name: "ğŸ”¨ Steffo's Python Poetry Workflow"
#
# on:
#   push:
#     branches:
#       - main
#       - master
#   pull_request:
#     branches:
#       - main
#       - master
#   schedule:
#     - cron: "10 10 * * 1"  # Every monday at 10:10 AM
#   release:
#     types:
#       - published
#   workflow_dispatch:
#
# defaults:
#   run:
#     shell: bash
#
# jobs:
#
#   build-package:
#     name: "ğŸ“¦ Build and publish Python package"
#     runs-on: ubuntu-latest
#     if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
#
#     steps:
#       - name: "â¬‡ï¸ Checkout repository"
#         uses: actions/checkout@v3
#
#       - name: "ğŸ”¨ Setup Python"
#         uses: actions/setup-python@v3
#
#       - name: "ğŸ”¨ Setup Poetry"
#         uses: abatilo/actions-poetry@v2.1.4
#
#       - name: "ğŸ”¨ Setup Poetry Python environment"
#         uses: Steffo99/actions-poetry-deps@0.2.3
#
#       - name: "ğŸ— Build package with Poetry"
#         run: poetry build --no-interaction
#
#       - name: "â¬†ï¸ Upload code package as artifact"
#         uses: actions/upload-artifact@v3
#         with:
#           name: "package.tar.gz"
#           path: dist/*.tar.gz
#
#       - name: "â¬†ï¸ Upload wheel package as artifact"
#         uses: actions/upload-artifact@v3
#         with:
#           name: "package.whl"
#           path: dist/*.whl
#
#       - name: "Publish Poetry package"
#         run: poetry publish --no-interaction
#         env:
#           POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
#
#   build-docs:
#     name: "ğŸ“” Build and publish documentation"
#     runs-on: ubuntu-latest
#     needs: build-package
#     if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
#
#     steps:
#       - name: "â¬‡ï¸ Checkout repository"
#         uses: actions/checkout@v3
#
#       - name: "ğŸ”¨ Setup Python"
#         uses: actions/setup-python@v3
#
#       - name: "ğŸ”¨ Setup Poetry"
#         uses: abatilo/actions-poetry@v2.1.4
#
#       - name: "ğŸ”¨ Setup Poetry Python environment"
#         id: pyenv
#         uses: Steffo99/actions-poetry-deps@0.2.3
#
#       - name: "ğŸ— Build HTML documentation with Sphinx"
#         working-directory: docs/
#         run: |
#           source ${{ steps.pyenv.outputs.pyenv }}/activate
#           make html
#
#       - name: "â¬†ï¸ Upload docs artifact"
#         uses: actions/upload-artifact@v3
#         with:
#           name: "documentation"
#           path: "docs/build/html/"
#
#       - name: "ğŸŒï¸ Publish build to GitHub Pages"
#         uses: peaceiris/actions-gh-pages@v3.8.0
#         with:
#           github_token: "${{ secrets.GITHUB_TOKEN }}"
#           publish_dir: "docs/build/html/"
#           enable_jekyll: false
#